COMPILER=g++
CCFLAGS= -Wall
all: main
langbuilder: flex --outfile=src/query/interpreter/lexer/lex.yy.c src/query/lexer/lang.l
			bison --output=src/query/interpreter/lexer/parser.tab.c -d src/query/parser/parser.y
			$(COMPILER) -Wall src/query/lexer/lexer.cpp -o src/query/lexer/lexer