#define IDENTIFIER 1
#define MATCH 2
#define RETURN 3
#define COLON 4
#define OPEN_C_BRACE 5
#define CLOSE_C_BRACE 6
#define OPEN_PARENTHESIS 7
#define CLOSE_PARENTHESIS 8
#define OPEN_BRACE 9
#define CLOSE_BRACE 10
#define NOT 11
#define WHERE 12
#define EQUALS 13
#define GREATER_THAN 14
#define LOWER_THAN 15
#define APOTSTROPHE 16
#define QUOTATION_MARK 17
#define INTEGER 18
#define DECIMAL 19
#define DOT 20
#define ARROW_TO_LEFT 21
#define ARROW_TO_RIGHT 22
#define HYPHEN 23
#define COMA 24
#define CONTAINS 25
#define STARTS 26
#define ENDS 27
#define WITH 28
#define PRIME 29 //VIRGUILILLA
#define ASTERISK 30
#define EOL 31
#define STRING 32