// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: network.proto

#include "network.pb.h"
#include "network.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace network {

static const char* QueryService_method_names[] = {
  "/network.QueryService/ExecuteQuery",
};

std::unique_ptr< QueryService::Stub> QueryService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< QueryService::Stub> stub(new QueryService::Stub(channel));
  return stub;
}

QueryService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ExecuteQuery_(QueryService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status QueryService::Stub::ExecuteQuery(::grpc::ClientContext* context, const ::network::Query& request, ::network::QueryResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ExecuteQuery_, context, request, response);
}

void QueryService::Stub::experimental_async::ExecuteQuery(::grpc::ClientContext* context, const ::network::Query* request, ::network::QueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, std::move(f));
}

void QueryService::Stub::experimental_async::ExecuteQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::network::QueryResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, std::move(f));
}

void QueryService::Stub::experimental_async::ExecuteQuery(::grpc::ClientContext* context, const ::network::Query* request, ::network::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, reactor);
}

void QueryService::Stub::experimental_async::ExecuteQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::network::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ExecuteQuery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::network::QueryResponse>* QueryService::Stub::AsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::network::QueryResponse>::Create(channel_.get(), cq, rpcmethod_ExecuteQuery_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::network::QueryResponse>* QueryService::Stub::PrepareAsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::network::QueryResponse>::Create(channel_.get(), cq, rpcmethod_ExecuteQuery_, context, request, false);
}

QueryService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      QueryService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< QueryService::Service, ::network::Query, ::network::QueryResponse>(
          std::mem_fn(&QueryService::Service::ExecuteQuery), this)));
}

QueryService::Service::~Service() {
}

::grpc::Status QueryService::Service::ExecuteQuery(::grpc::ServerContext* context, const ::network::Query* request, ::network::QueryResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace network

