// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: network.proto
#ifndef GRPC_network_2eproto__INCLUDED
#define GRPC_network_2eproto__INCLUDED

#include "network.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace network {

class QueryService final {
 public:
  static constexpr char const* service_full_name() {
    return "network.QueryService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status ExecuteQuery(::grpc::ClientContext* context, const ::network::Query& request, ::network::QueryResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::network::QueryResponse>> AsyncExecuteQuery(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::network::QueryResponse>>(AsyncExecuteQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::network::QueryResponse>> PrepareAsyncExecuteQuery(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::network::QueryResponse>>(PrepareAsyncExecuteQueryRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void ExecuteQuery(::grpc::ClientContext* context, const ::network::Query* request, ::network::QueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::network::QueryResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ExecuteQuery(::grpc::ClientContext* context, const ::network::Query* request, ::network::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void ExecuteQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::network::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::network::QueryResponse>* AsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::network::QueryResponse>* PrepareAsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status ExecuteQuery(::grpc::ClientContext* context, const ::network::Query& request, ::network::QueryResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::network::QueryResponse>> AsyncExecuteQuery(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::network::QueryResponse>>(AsyncExecuteQueryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::network::QueryResponse>> PrepareAsyncExecuteQuery(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::network::QueryResponse>>(PrepareAsyncExecuteQueryRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void ExecuteQuery(::grpc::ClientContext* context, const ::network::Query* request, ::network::QueryResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecuteQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::network::QueryResponse* response, std::function<void(::grpc::Status)>) override;
      void ExecuteQuery(::grpc::ClientContext* context, const ::network::Query* request, ::network::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void ExecuteQuery(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::network::QueryResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::network::QueryResponse>* AsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::network::QueryResponse>* PrepareAsyncExecuteQueryRaw(::grpc::ClientContext* context, const ::network::Query& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExecuteQuery_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ExecuteQuery(::grpc::ServerContext* context, const ::network::Query* request, ::network::QueryResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExecuteQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExecuteQuery() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExecuteQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteQuery(::grpc::ServerContext* /*context*/, const ::network::Query* /*request*/, ::network::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteQuery(::grpc::ServerContext* context, ::network::Query* request, ::grpc::ServerAsyncResponseWriter< ::network::QueryResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExecuteQuery<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_ExecuteQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_ExecuteQuery() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::network::Query, ::network::QueryResponse>(
          [this](::grpc::ServerContext* context,
                 const ::network::Query* request,
                 ::network::QueryResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->ExecuteQuery(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_ExecuteQuery(
        ::grpc::experimental::MessageAllocator< ::network::Query, ::network::QueryResponse>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::network::Query, ::network::QueryResponse>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_ExecuteQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteQuery(::grpc::ServerContext* /*context*/, const ::network::Query* /*request*/, ::network::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ExecuteQuery(::grpc::ServerContext* /*context*/, const ::network::Query* /*request*/, ::network::QueryResponse* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_ExecuteQuery<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExecuteQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExecuteQuery() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExecuteQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteQuery(::grpc::ServerContext* /*context*/, const ::network::Query* /*request*/, ::network::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExecuteQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExecuteQuery() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExecuteQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteQuery(::grpc::ServerContext* /*context*/, const ::network::Query* /*request*/, ::network::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExecuteQuery(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_ExecuteQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_ExecuteQuery() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->ExecuteQuery(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_ExecuteQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExecuteQuery(::grpc::ServerContext* /*context*/, const ::network::Query* /*request*/, ::network::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void ExecuteQuery(::grpc::ServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ExecuteQuery : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ExecuteQuery() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::network::Query, ::network::QueryResponse>(std::bind(&WithStreamedUnaryMethod_ExecuteQuery<BaseClass>::StreamedExecuteQuery, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_ExecuteQuery() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExecuteQuery(::grpc::ServerContext* /*context*/, const ::network::Query* /*request*/, ::network::QueryResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedExecuteQuery(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::network::Query,::network::QueryResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_ExecuteQuery<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_ExecuteQuery<Service > StreamedService;
};

}  // namespace network


#endif  // GRPC_network_2eproto__INCLUDED
